### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [LukasFibiger/zbozicz-Tag-For-SGTM#1]
https://github.com/LukasFibiger/zbozicz-Tag-For-SGTM/blob/32e78dea4b58553fe0780975d2dacc53268301a7/template.tpl#L164

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by LukasFibiger** [comment]
Hi, I thank you. I update this code.
